### ISSUE TITLE
Error: RangeError [ERR_OUT_OF_RANGE]: The value of "sourceStart" is out of range

### ISSUE THREAD

**Issue by vitali-gm** [dmitrygorkun/sypex-geo#1]
```javascript
   
    import {SypexGeoClient} from "@gorkun/sypex-geo";

    const client = new SypexGeoClient( 'geo/SxGeoCity.dat')
    const city = client.get('31.132.162.56');
    console.log(city)
```

![image](https://user-images.githubusercontent.com/17673354/94570726-cedebe00-0277-11eb-9d44-1d920f65492f.png)

**Comment by dmitrygorkun** [comment]
Hey.
Thanks for the issue.
Something strange is really happening with this IP, and even on the official website.
I will fix the error handling for such cases.

![Screen Shot 2020-10-02 at 12 43 59 PM](https://user-images.githubusercontent.com/4750533/94910338-48132680-04ad-11eb-81fe-0ffc6d7047c2.png)

**Comment by vitali-gm** [comment]
Thanks for the answer. I found that only at latitude: 60 and longitude: 100 there is such a problem

**Comment by dmitrygorkun** [comment]
@sypexgeo Can U comment this issue?
